<?php
$helperPermission = $this->helper('Magestore\Webpos\Helper\Permission');
$webposShowContent = ($helperPermission->getCurrentUser() && !$helperPermission->isShowChoosePosLocation())?true:false;
if($webposShowContent){
?>
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PVJSMVD" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!--end edit setup livechat when customer login -->
<a href="#" class="open-pannel"><img src="<?php echo $this->getViewFileUrl('Magestore_Tutorial::images/tutorial-icon.png'); ?>" /><span>Tutorial<br/>Menu</span></a>
<div class="tutorials-panel">
	<div class="tutorials-panel-default">
		<div class="tutorials-panel-header">
			<strong class="title">Tutorial for WebPos</strong>
			<a href="#" class="clone-pannel"><span>Close panel</span></a>
		</div>
		<div class="tutorials-panel-content">			
			<ul class="list">
				<!--li><a href="#" id="intro-webpos1" class="intro">Opening Session</a></li-->
				<li><a href="#" id="intro-webpos1" class="intro">Session Management</a></li>
				<li><a href="#" id="intro-webpos2" class="intro">Making Order</a></li>				
				<li><a href="#" id="intro-webpos3" class="intro">Refunding Order </a></li>
				<!--li><a href="#" id="intro-webpos4" class="intro">Ending Session</a></li-->
				<li><a href="http://demo-magento2.magestore.com/omnichannel/starter/02/admin" id="intro-webpos4" class="intro">Back to main Tutorial</a></li>
			</ul>						
		</div>
		<div class="tutorials-panel-bottom">			
			<div class="detail">				
				<p class="title">Feel Free to contact if you have any questions about the solution</p>
				<div class="actions">
					<a href="javascript:void(0)" onclick="$zopim.livechat.window.show(); ga('send', {'hitType': 'event', 'eventCategory': 'Demo OMC starter', 'eventAction': ' WebPos', 'eventLabel': 'Contact-us'});" class="btn">Talk to Sales</a>
					<a target="_blank" onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Demo OMC starter', 'eventAction': ' WebPos', 'eventLabel': 'Buy-now'});"  href="//magestore.com/pricing?starter" class="btn btn-orange">Buy Now</a>
				</div>
				
			</div>
		</div>
	</div>
</div>
	<?php
}
?>
