<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PVJSMVD" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

<a href="#" class="open-pannel"><img src="<?php echo $this->getViewFileUrl('Magestore_Tutorial::images/tutorial-icon.png'); ?>" /><br><span>Tutorial <br> Menu</span></a>

<div class="tutorials-panel">
	<div class="tutorials-panel-default">
		<div class="tutorials-panel-header">
			<strong class="title">Tutotial Menu</strong>
			<a href="#" class="clone-pannel"><span>Close panel</span></a>
		</div>
		<div class="tutorials-panel-content">
			
			<h4 class="titel">WebPOS:</h4>
			<ul class="list">
				<!-- <li><a href="#" id="intro1" class="intro"> General Configure</a></li> -->
				<li><a href="#" id="webpos1" class="intro">Config POS Backend </a></li>
				<!-- <li><a href="#"  id="webpos2" class="intro">Sales at POS Frontend</a></li> -->
				
			</ul>
			<br>
			<h4 class="titel">Inventory Management:</h4>
			<ul class="list">
				<li><a href="#" id="inventory1" class="intro">New Stocktaking</a></li>
				<li><a href="#" id="inventory2" class="intro">New Stock Adjustment</a></li>
				<li><a href="#" id="inventory3" class="intro">Goods Receipt/ Goods Delivery</a></li>
				<li><a href="#" id="inventory5" class="intro">Stock Listing in Warehouse</a></li>
				<li><a href="#" id="inventory4" class="intro">Supply Needs & Low Stock Alert</a></li>
				
			</ul>
			
			
		</div>
		<div class="tutorials-panel-bottom">			
			<div class="detail">				
				<p class="title">Feel Free to contact if you have any questions about the solution</p>
				<div class="actions">
					<a href="javascript:void(0)" onclick="$zopim.livechat.window.show(); ga('send', {'hitType': 'event', 'eventCategory': 'Demo OMC starter', 'eventAction': ' WebPos', 'eventLabel': 'Contact-us'});" class="btn">Talk to Sales</a>
					<a target="_blank" onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Demo OMC starter', 'eventAction': ' WebPos', 'eventLabel': 'Buy-now'});"  href="//www.magestore.com/pricing?starter" class="btn btn-orange">Buy Now</a>
				</div>
				
			</div>
		</div>
	</div>
</div>

<style type="text/css">

	.modal-slide .modal-inner-wrap {
		width: 100% !important;
	}

	

	.menu-wrapper {
		position: relative !important;
		top: 0 !important;
		float: left;
	}

	.menu-wrapper._fixed ~ .page-wrapper {
		margin-left: 0 !important;
	}

	.page-actions-placeholder {
		height: 0 !important;
		min-height: 0 !important;
	}

	.introjs-next-tutorial {
		padding: 0 15px;
		color: #fff;
		border-radius: 4px;
		margin-left: 5px;
	}
</style>

